networks:
  backend:

services:
  mariadb:
    image: wodby/mariadb:latest
    stop_grace_period: 30s
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testclass
      MYSQL_USER: testclass
      MYSQL_PASSWORD: testclass
    networks:
      - backend
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: mariadb
      PMA_VERBOSES: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - backend
  php:
    image: wodby/php:8.1
    environment:
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - ./:/var/www/html
    networks:
      - backend
  nginx:
    image: wodby/nginx:latest
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      NGINX_VHOST_PRESET: php
    volumes:
      - ./:/var/www/
    ports:
      - 8000:80
    networks:
      - backend
